apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  namespace: whoami
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: whoami.sost.ovh
    http:
      paths:
      - path: /
        backend:
          serviceName: whoami
          servicePort: 80
  tls:
    - secretName: whoami-tls-prod-cert
      hosts:
        - whoami.sost.ovh
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami-internal
  namespace: whoami
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: whoami.internal.sost.ovh
    http:
      paths:
      - path: /
        backend:
          serviceName: whoami
          servicePort: 80
  tls:
    - secretName: whoami-internal-tls-prod-cert
      hosts:
        - whoami.internal.sost.ovh
