apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
data:
  qBittorrent.conf: |
    [AutoRun]
    enabled=false
    program=

    [Core]
    AutoDeleteAddedTorrentFile=Never

    [Preferences]
    Advanced\RecheckOnCompletion=false
    Advanced\trackerPort=9000
    Connection\PortRangeMin=29451
    Connection\ResolvePeerCountries=true
    Downloads\SavePath=/downloads/
    Downloads\TempPath=/downloads/temp/
    DynDNS\DomainName=changeme.dyndns.org
    DynDNS\Enabled=false
    DynDNS\Password=
    DynDNS\Service=0
    DynDNS\Username=
    General\Locale=
    MailNotification\email=
    MailNotification\enabled=false
    MailNotification\password=
    MailNotification\req_auth=true
    MailNotification\req_ssl=false
    MailNotification\sender=qBittorrent_notification@example.com
    MailNotification\smtp_server=smtp.changeme.com
    MailNotification\username=
    Queueing\QueueingEnabled=false
    Scheduler\days=0
    Scheduler\end_time=@Variant(\0\0\0\xf\x4J\xa2\0)
    Scheduler\start_time=@Variant(\0\0\0\xf\x1\xb7t\0)
    WebUI\Address=*
    WebUI\AlternativeUIEnabled=true
    WebUI\AuthSubnetWhitelist=10.0.0.0/10
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\BanDuration=3600
    WebUI\CSRFProtection=true
    WebUI\ClickjackingProtection=true
    WebUI\CustomHTTPHeaders=
    WebUI\CustomHTTPHeadersEnabled=false
    WebUI\HTTPS\CertificatePath=
    WebUI\HTTPS\Enabled=false
    WebUI\HTTPS\KeyPath=
    WebUI\HostHeaderValidation=false
    WebUI\LocalHostAuth=false
    WebUI\MaxAuthenticationFailCount=5
    WebUI\Port=8080
    WebUI\RootFolder=/app/vuetorrent
    WebUI\SecureCookie=true
    WebUI\ServerDomains=*
    WebUI\SessionTimeout=3600
    WebUI\UseUPnP=false
    WebUI\Username=admin
