apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: qbittorrent
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: qbittorrent.sost.ovh
    http:
      paths:
      - path: /
        backend:
          serviceName: qbittorrent
          servicePort: 80
