apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-creds
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAUErkXVSTocphltz6hHirYFmAuskKxg5KIUQvVa3DjJ7oiEMsRCV7ZXQx2S+YH80kkEb+AtWgdmNlK7HI6gj0OrvPa3yM1qtXPJPOC1lmjNias4irKaBXOpbdizO+SIEQBtex66ZKfWxqNRRwpzHgcHAUwsVZRB6KiFa7H7ooASDaZA9Piuj3TpqH7F5C3AsLv+NZabh6F4rJm2zdE32tIVuhJ4vZzLLf2IFZgikKy8kzU8fhbkzpS5xvABPhzYonvYdDpffrP5NVGS9FFKqknB3ZeUZqgPDPeUjlYtZnUpRDC2BKJWpKmSaKKAftK0uUnLxiQR4J8DMIhZJ1UVCU7dtN+VYYpHQlEzb0XyVJP9YYR/aOPwBW7VKhmPKRZZvW1Nlx3Rk1nYpIM9KM06sm6yvpwhBdxb3aJINyMUvdUWaANQ0YjS+CVLSinUYRnBRkE4g61HgMGl4JjBwUpJTVxgA+r6ErOetIl/ED+9wSU5eC4e6v9Z3l3OVGH80VRsiWGuguphd3C9bs4qCnXO2/a9StUpMw37PYRPz0olDrNFi9o4xfCGkhtDxARiq1pr2C2wpp/CUhtC2w43pMKjJ1JLm6he8wHiZ8fcH5PfcoBoHZJjLqpG41z1atfzWfVyP6TtoRR1plCTpadW8jYb4/2noTRlNydgQoz7NHDaA+jrnoD7pGEijEHeQhqP6uB5Up4eM0ZwVCX8gGgXsDgl7PAA19bz/MFyqaUfNeCnEURFF16/RqQSq6T
    GF_SECURITY_ADMIN_USER: AgAUuDk05/B3i5fB2Fq4iKlWQAvW4obfl4yMONE7QQUAvcCz0uwjPgcxJRPjeCIb/PivooVdE8cyYpgC6XTA7T7KmicSgkgNZQtwixzBYDpaWykO0AnWnSbMAQk9H/Ql70B/+eq1BO8WUuLYb+pgp54yW+eLPaZiAQY2Fq3EEMSpajKAXjCNg9G4m7gY/lAYRnkmMT9bgvvfigGkXb+JJuyUNzqhFdeg3pYVQe9XE9EjlLb/FZ3d+iB+9NbfYmsHvBgQ8PZy2TouYWEYIdf+sA2/t+VhVpcKeIGc0WzeOIpPHzPXddG1cw5PTLcVwrbZoz8NugfNgctQarCk3qzdBXYxJ34zwmMvVFb0aKdR3dQazgC2sO1cXGiNW8MDV9lhkyp2S6A/6LyyclciygjNSqmgEHx0nrBDQa4I2MWhD/fZxv9fI4WYlNIxFwoVMGlPesnsP1feNpAA1pVEoIJN0GaYXIG1nnooLKdYm23kfROwx5BkGi9pLbFDOJ3VTtyql/WZIufo40kToUb2j5ayQXFECmpgXT931tb3Ia8+R7rTNtiWMxKNpCcDQwS7cyXgt1BsZDV6v7xXvg6Qoll7puKn2o0KXuGMEDGt0eFGtN5kHCB1cUUZcfiROPvOiBDzTpDzKBeyPQrI44FPvjwjMqMtt7IBJoF4oZoTshn64eeUGwMhm6JAiegFtLSyWTkdV2D/uYe6Fg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-creds
      namespace: monitoring
    type: Opaque

