apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
  namespace: plex
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: plex.sost.ovh
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: 32400
