apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: homer
data:
  config.yml: |
    ---
    # Homepage configuration
    # See https://fontawesome.com/icons for icons options

    # Optional: Use external configuration file. 
    # Using this will ignore remaining config in this file
    # externalConfig: https://example.com/server-luci/config.yaml

    title: "Homelab Dashboard"
    # subtitle: "Homer"
    # documentTitle: "Welcome" # Customize the browser tab text
    logo: "assets/logo.png"
    # Alternatively a fa icon can be provided:
    # icon: "fas fa-skull-crossbones"

    header: true # Set to false to hide the header
    footer: false # set false if you want to hide it.

    columns: "2" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
    connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

    # Optional theming
    theme: default # 'default' or one of the themes available in 'src/assets/themes'.

    # Optional custom stylesheet
    # Will load custom CSS files. Especially useful for custom icon sets.
    # stylesheet:
    #   - "assets/custom.css"

    # Here is the exhaustive list of customization parameters
    # However all value are optional and will fallback to default if not set.
    # if you want to change only some of the colors, feel free to remove all unused key.
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#424242"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link-hover: "#363636"
        background-image: "assets/your/light/bg.png"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link-hover: "#ffdd57"
        background-image: "assets/your/dark/bg.png"

    # Optional message
    message:
      # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
      # mapping: # allows to map fields from the remote format to the one expected by Homer
      #   title: 'id' # use value from field 'id' as title
      #   content: 'value' # value from field 'value' as content
      # refreshInterval: 10000 # Optional: time interval to refresh message
      #
      # Real example using chucknorris.io for showing Chuck Norris facts as messages:
      # url: https://api.chucknorris.io/jokes/random
      # mapping:
      #   title: 'id'
      #   content: 'value'
      # refreshInterval: 10000

    # Optional navbar
    # links: [] # Allows for navbar (dark mode, layout, and search) without any links
    links:
      - name: "Kubernetes Config"
        icon: "fab fa-github"
        url: "https://github.com/hugomd/kubernetes-homelab"

    # Services
    # First level array represents a group.
    # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
    services:
      - name: "Media"
        icon: "fas fa-play-circle"
        # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
        # logo: "path/to/logo"
        items:
          - name: "Plex"
            # logo: "assets/tools/sample.png"
            # Alternatively a fa icon can be provided:
            icon: "fas fa-play-circle"
            tag: "media"
            url: "https://plex.sost.ovh"
          - name: "Qbittorrent"
            # logo: "assets/tools/sample.png"
            # Alternatively a fa icon can be provided:
            icon: "fas fa-download"
            tag: "media"
            url: "https://qbittorrent.sost.ovh"
      - name: "Utility"
        icon: "fas fa-heartbeat"
        items:
          - name: "Authelia"
            url: "https://authelia.sost.ovh"
            icon: "fas fa-lock"
      - name: "Networking"
        icon: "fas fa-server"
        items:
          - name: "Ubiquiti"
            url: "https://unifi.ui.com"
            icon: "fas fa-server"
          - name: "NextDNS"
            url: "https://my.nextdns.io"
            icon: "fas fa-book"
          - name: "whoami"
            url: "https://who.sost.ovh"
            icon: "fas fa-user"
      - name: "Monitoring"
        icon: "fas fa-heartbeat"
        items:
          - name: "Grafana"
            url: "https://grafana.sost.ovh"
            icon: "fa fa-exclamation-circle"
