apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sosto-tunnel-1
  namespace: ingress-nginx
spec:
  encryptedData:
    credentials.json: AgB4O52KtvuMINSDFykCnhNUencrWHhYyQcI/V9iIaeSIPNif53KlJuoj5XKYw9xg59P4eN1KDeN9eF3EKOS+BM86Rnqlm8cwNRHihiUlWIwlV9zMEy1ajyd5Mxhkd4drPjQas5kolDiqx6RDwRO2L5rG+BKRE/z93IqvCzePNfsm9BlEeasntbTyoKW5+r0wMAJWds9TR0R9NsgOR2Vyb0afF5J8ca8RyZZpThPFp5MfWasITvHsJYZg8S0kYTTraoTZJHDUChfLpHqhwBhUyLgxiQSVZ5OWyVqqpPzTJ/PKT4eT9ThBrtWljtBYJ7gu9AmPKytMOoyKGW34/Tcz9OpK9ht3h6RzL8HAwETmw02DyihJIzLiAv9NXgk9+ubXlNBVgLE0+O6PrJal6hNGrpgIagD3I/pkjQa5RqglNe7NOldstDUFTFo93RTtUdEtFgdJI6Yp3lfgIUdBeAg3KFrYRMXiNVN0bbjMv3KPgHqh+NeiHXwdhIjcAssmWRNA/cQgTE2HR03EaCLVxkRsJTRFFclKG6+Z9DXYQrXMbvulDSZEIJKiuQ/m6B7kIbhAGYZv2kt7VbSG7FcymkjzxpEwz407gf/QydcO9X+Kbjteq5/H/2DNlyuY5n4KgjkjNMJb3PfiKIBMPz3sFEVCs9gA/0FgMiI6lZFr7HWonyyqCvfpckn8VcIV4zLkP4KyU+SkzOJmoZL0ZQq/sVdRqtVs0+AP6/prSMIef4SlSiXgQ9Pn/dMZ+BP1M6UYJTlrfHShkhFo1lvqPAPAfooDsjL4ojCk2yP3nADX9OMtRhJ1bZ6iZKrlcELtAGp8xsJ1qX66LJL5DD18CNeZwEJg5iOybiIlAk0le7KJtWFw0D4YQS/UTghkXflbU5LJhGWZS7cq8gArXCR/UXJ2h328u9kuRLDqduieTu0XvZYI7pyk74iGTm4dXxnCPWQxAnfeg==
  template:
    metadata:
      creationTimestamp: null
      name: sosto-tunnel-1
      namespace: ingress-nginx
    type: Opaque

