kind: ConfigMap
metadata:
  annotations:
  name: config
  namespace: metallb-system
apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250

