apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: speedtest-config
  namespace: monitoring
spec:
  encryptedData:
    config.ini: AgAjXIW+KQk/or5T+02F7trnbntjlTPj4gG5efkrlKmV23T1h9GX8wcW0o6eiH4pYkoLDUl2U5vnARIoFPrvNczCZ9VeWHfY6kc3wQCKDm9iximl/6aK2aLL5JMEWf6ucvxPFKB6buflB8aF2lcwLd4007GuyyqGZnZmEfZFrdvwhHTKgsWQks84zxxO8KJ4VQSIxDza/MpBGIhtRh/fyYn8JelN7kMSQ+fkPUuQ040m18ztXNVbiF9wvKWxF0p14egUP9fvZIi46cG7fusCqIfDtdb7df72xIK+6YRi2xA6wqRpd05a95HWOL6BeCxu9BRynORUKNeuvZjPziOrPGPYYWPu2n7yoBBVTMHS8NSFQw0/X0kohDiahov+SqB5+5CN+paSqEQI1IdQRUnyRku+4ttNBlm+EYr9HK5hHX+T5Q7+L1pHdI/uUkkpo+MzpNSbQf7b8Dj8yO3MNBl0CRxRaQf1KhiHgdeF78KnTrAcjjmGHb75AVzCuDgCiQmZGb6qT7lIJ54oJniM4PFNrCOzYNkaf+5/c8fELG3Cfwz9uEB1Sasc1HLa3NEgyAgeg+JV+gs1X7Rb3RUtL6tC8O7Dgboqr8q5/spkCDPRMZzwQSV3srH/PhcRpIH38IVWzhhaU5EAnnkVFJaTI6W8jtyQG/WYdt8WakAITQ2LV8ctQEK2PCwLhUt5HcaXFo5qomT1TqBJFGIsKjwb7Y9ygN9p6nslqPIsG+Bqc7BBO6epx9QmwLAYyl5T6NckUVKx7AgRv2h5heML/WYK8vW8dHQBgK/qkdZwb6kY57kerZfIH4PGepdgf00Io9YXF9JpV2k7Sa9gI/lfz0q7bEbeCINvTJvs5Dc7PNj415eZFsGJetR325c6/8QK0xW+Joxb5RyFq0xYAf6ZTawe/9WjHXQcTmMfwwCX1ToUgse30dGzCJrW2R7Ff999VPz66turUhsoo2VVkr5IAsds+GGk+kXBzB1rEu765EgsMTcbb86CAFXpIgrvMnj4O2CbJF8mtlNZ1pkBAQz4hIm7RmKTqV98YxvTdynrQxGrI7DiPbvTPohFe3f23JMugi+UNdKhDcYfKy/vopvWY57Sbm/Kk35Q
  template:
    metadata:
      creationTimestamp: null
      name: speedtest-config
      namespace: monitoring

